services:
  app:
    build: .
    platform: linux/amd64
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: npm start
    ports:
      - 8080:8080

  npm:
    extends:
      service: app
    entrypoint: npm
    profiles:
      - cli

  npx:
    extends:
      service: app
    entrypoint: npx
    profiles:
      - cli
